spring:
  application:
    name: CONFIG-SERVER
    
  cloud:    config:      server:        git:          uri: https://github.com/rohitdhingra/cloud-config-server
    
server:  port: 9196
  

eureka:  client:    enabled: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8761/eureka  
  instance:
    hostname: localhost