server:
  port: 9192
  
spring:  h2:    console:      enabled: true
      
  application:    name: ORDER-SERVICE
    
logging:
  file: C:\Users\Rohit Dhingra\git\ApiGatewayEurekaHystrixRep\logs\microservice.log